[default.databases.website]
url = "postgresql://percy:warmachine68@192.168.178.149/website"

[static]
uri = "/static"
dir = "templates"

[template]
engines = { handlebars = ["templates"] }
dir = "templates"

[global.limits]
file = 104857600  # 100 MB
forms = 104857600  # 100 MB