[default.databases.percy]
url = "postgresql://percy:warmachine68@104.248.255.90/percy"

[static]
uri = "/static"
dir = "frontend"

[template]
engines = { handlebars = ["templates"] }
dir = "templates"

[global.limits]
file = 104857600